### ISSUE TITLE
Unable to connect to real CICS region 

### ISSUE THREAD

**Issue by MN-Mike** [galasa-dev/projectmanagement#151]
[ProblemDoc.zip](https://github.com/galasa-dev/projectmanagement/files/4441128/ProblemDoc.zip)

I wanted to try to connect to a real CICS region. 

The zip file attached is the overrides file that documents and JVMEnabledTest.java test as well as a console.log with trace on and a network capture text file of a PCOMM session doing the same process and the GALASA session. 

The test connects to the LPAR, performs a LOGON APPLID(xxx), then CESN, CLEAR, CESF LOGOFF, disconnect.  But it is not getting into the region.

It appears the PCOMM is doing an UNBIND / BIND-IMAGE, the GALASA session is not recognizing the UNBIND.

**Comment by hobbit1983** [comment]
@MN-Mike Thanks for raising the issue.  Thanks for sending such a comprehensive amount of documentation.  We are taking a look

**Comment by MN-Mike** [comment]
I realized there are some messages in the CICS region from the Terminal Autoinstall that might be relevant, so I uploaded those too, both PCOMM and GALASA. In the PCOMM just connected to the region and CESF LOGOFF.  GALASA appears to have not fully established
[msgusr notes.txt.txt](https://github.com/galasa-dev/projectmanagement/files/4445857/msgusr.notes.txt.txt)
 up so it disconnected.

**Comment by hobbit1983** [comment]
Cheers Mike.  Your TCP/IP trace was most enlightening.  I think I have a change set in my fork that should allow things to connect.  I saw in the trace that z/OS was sending a IAC DO TIMING_MARK request. which we currently do not cater for, so my fix alters that behaviour.  I will examine the extra diagnostics tomorrow and see what I learn from them.  As for building the managers yourself we are pulling together some notes for you.  However I do know that you will need maven installed as a command line tool.  Is this available on your workstation?

**Comment by MN-Mike** [comment]
It may be, I will take a look at getting Maven installed. My SNA / low level coding days were decades back but I was taking it as a challenge but I would need to relearn the protocols that you are already familiar with so it would be quicker for you.

I would need some hand holding to get the build to work locally and get it installed in my running galasa, it might be quicker to get a patch from you at this time while I learn how to build the project.

Thank you.

____________________________
Mike Baillargeon | Optum Technology
Director. zSystems CICS and DB Support

6150 Trenton Lane North, Plymouth, Minnesota 55442
T     +1 763-337-8716
M     +1 612-760-7474
Mike.Baillargeon@optum.com<mailto:Mike.Baillargeon@optum.com>

**Comment by hobbit1983** [comment]
I've just merged a change to the 3270 manager that should allow us to tolerate the TIMING_MARK requests.  which will be part of 0.7.0. are you happy to try and build galasa from our snapshots build of 0.7.0 or would you like a patched version for 0.6.0?

Either way we will try and get some information to you.

**Comment by MN-Mike** [comment]
I have not been able to get the build to work, but I do have command line maven (but no experience with it yet).  If a build is easier I can do that, whatever you think might be easier to setup.

____________________________
Mike Baillargeon | Optum Technology
Director. zSystems CICS and DB Support

6150 Trenton Lane North, Plymouth, Minnesota 55442
T     +1 763-337-8716
M     +1 612-760-7474
Mike.Baillargeon@optum.com<mailto:Mike.Baillargeon@optum.com>

**Comment by hobbit1983** [comment]
Hi Mike,

I've submitted a fix that should allow you to access your mainframe system.  It is currently at our daily build of 0.7.0-SNAPSHOT which you can access by installing from https://p2snapshot.galasa.dev instead of p2.galasa.dev.  

If you are looking to to go and edit and pay with the entire SNAPSHOT that we are currently developing then you can go and pull the following repos:
	galasa-dev/framework
	galasa-dev/managers
	galasa-dev/extensions
	galasa-dev/maven
	galasa-dev/wrapping

To build galasa from scratch, you have to run the maven install commands in each repository in the right order to make sure that the dependancies for other project are built before building them, the order is as follows:

1. mvn install -f <location>/maven/galasa-maven-plugin
2. mvn install -f <location>/wrapping/
3. mvn install -f <location>/framework/galasa-parent
4. mvn install -f <location>/extensions/galasa-extensions-parent
5. mvn install -f <location>/managers/galasa-managers-parent

This will go away and install all of the necessary galasa artefacts into your local maven repo (can check by `ls ~/.m2/repository/dev/galasa/dev.galasa.uber.obr/` which should show all the version of galasa that you have locally)

To speed things up you can use our external maven repository where we host the nightly snapshot builds of 0.7.0 which is available at https://nexus.galasa.dev/repository/maven-development/. You can add this to your maven settings.xml as a separate repository, this means during the build, maven can download components from here so you would only have to build the manager or repository that you are interested in.

If you are running galasa in eclipse you can change the Remote Maven URI to be https://nexus.galasa.dev/repository/maven-development/ and the OBR version to be 0.7.0-SNAPSHOT

**Comment by MN-Mike** [comment]
Will, I apologize for taking so long to respond.  I have been ill for the last couple weeks (still not 100%).  It has been hard to sit up at my desk for any length of time during this period.

But I finally got the 070 snapshot downloaded and updated, unfortunately I am unable to get the framework to start, even with Simbank and now I am out of time again.  I will see how I feel tomorrow and try again.

____________________________
Mike Baillargeon | Optum Technology
Director. zSystems CICS and DB Support

6150 Trenton Lane North, Plymouth, Minnesota 55442
T     +1 763-337-8716
M     +1 612-760-7474
Mike.Baillargeon@optum.com<mailto:Mike.Baillargeon@optum.com>

**Comment by hobbit1983** [comment]
Mike - first sorry to hear you have been unwell, we hope that you are feeling well soon.  When you feel ready if you can attach any commands you are running and the errors you are seeing and we will get you moving again

**Comment by MN-Mike** [comment]
Finally got back to work and back to this.  I thought I would start with the basic SimbankIVT and that failed so I never got to my testing.   Attached is a zip with the console logs from the initialize framework, starting of Simbank and the SimbankIVT test.    I will run my test next and attach that as well.
[Galasa-Logs.zip](https://github.com/galasa-dev/projectmanagement/files/4552858/Galasa-Logs.zip)

**Comment by MN-Mike** [comment]
This log is the attempt to connect to the zOS Host.
[4.AttemptToZOSHost.console.log.txt](https://github.com/galasa-dev/projectmanagement/files/4552877/4.AttemptToZOSHost.console.log.txt)

**Comment by MN-Mike** [comment]
Looks like both test cases failed getting the ZosManagerImpl setup.

**Comment by hobbit1983** [comment]
Hi Mike - Great to hear that you are doing better and are back at work.  Thanks for the diagnostics.  We will take a look and get back to you.  Thanks again

**Comment by MN-Mike** [comment]
FYI, to install the snapshot, I downloaded the P2-snapshot directory contents and then did an update to the product that was installed (0.6.0).

**Comment by hobbit1983** [comment]
Hi Mike - I'm pretty sure that this is a problem with your cps or overrides properties not containing a cluster default, can you check that they are as detailed in the documentation here: https://galasa.dev/docs/getting-started/installing
and if you are still having problems can you send those two files in along with the annotated manager declarations at the top of your test class

**Comment by MN-Mike** [comment]
The cps file is empty, the overrides and the class source are in the zip attachment on the initial post.  I think the cluster for simbank and my cictsupa environment are there, but clearly I am not sure what I am doing so I may have messed it up.

Mike Baillargeon | Optum Technology
Director. zSystems CICS and DB Support

6150 Trenton Lane North, Plymouth, Minnesota 55442
T     +1 763-337-8716
M     +1 612-760-7474
Mike.Baillargeon@optum.com<mailto:Mike.Baillargeon@optum.com>

**Comment by MN-Mike** [comment]
Will, is there a way to remove Galasa from Eclipse so I can start over? Or do I need to remove Eclipse and start back at bare metal?

I am thinking I will wipe everything out, start over with the new 0.7.0 and confirm the issue still exists, then apply your snapshot if that makes sense.

**Comment by hobbit1983** [comment]
Mike - so the fix we talk about is now part of 0.7.0.  If you originally installed from p2.galasa.dev you should be able to update your plugin to 0.7.0

However if you wish to start again go to about eclipse and then select installation details.  Within the installed software dialog you should see 3 Galasa features:
Galasa Core
Galasa Simbank
Galasa zOS Feature

These can be selected and uninstalled
![image.png](https://images.zenhubusercontent.com/5dde9d89537fdc0001b7a126/d30299c8-d118-4678-a6dd-01c972b20802)

Eclipse will then restart and the plugin can then be re-installed.  I hope this helps and we can get you going!

**Comment by MN-Mike** [comment]
Will, I was able to remove Galasa from my Eclipse, the reinstall with 0.7.0 from the p2.galasa.dev contents. I tested with the IVT test and it worked once I updated  my overrides from localhost to 127.0.0.1 (not sure why I changed it). 

I then added my JVMEnabledTest class back and tested that but alas it failed again. I did have to work on my overrides to get it working, apparently 0.7.0 is more sensitive to upper/lower case matching than 0.6.0 was. 

Attached is a zip with a packet trace of a PCOM session connecting to the region, the Galasa session that fails, the .galasa files and the JVMEnabledTest.java class.  Let me know if you need anything else. 

[IssueDocs-2020-05-15.v.0.7.0.zip](https://github.com/galasa-dev/projectmanagement/files/4631421/IssueDocs-2020-05-15.v.0.7.0.zip)

**Comment by Michael-Baylis** [comment]
@MN-Mike One of the changes I made in 0.6.0 was to uppercase the tags and image ids in the zos manager,  to make it consistent and easier to spot the "dynamic" portions of the properties names.  This will be a standard across all the managers.

**Comment by Michael-Baylis** [comment]
@MN-Mike we have a similar issue when our session manager connects to a cics region.  It looks like the session manager is unlocking the keyboard before to hands over to the applid.
The way we get round this is, using your code:-
terminal.type("LOGON APPLID(UHGTSUPA)").enter();
terminal.waitForTextInField("xxxxx");  <--  put something in here to indicate the 3270 screen has moved to CICS,  a DFH message or the CSGM message
terminal.waitForKeyboard();
terminal.type("CESN").enter().waitForKeyboard();

**Comment by MN-Mike** [comment]
That explains the issue with the overrides. All good now.

____________________________
Mike Baillargeon | Optum Technology
Director. zSystems CICS and DB Support

6150 Trenton Lane North, Plymouth, Minnesota 55442
T     +1 763-337-8716
M     +1 612-760-7474
Mike.Baillargeon@optum.com<mailto:Mike.Baillargeon@optum.com>

**Comment by MN-Mike** [comment]
You got me thinking and I looked closer at the packet trace.  It looks like the LOGON APPLID was sent in with the CESN command, and our shop has a LOGO tran that terminates the session.  I added a clear().waitForKeyboard() before sending the CESN and it does work.  

Thank you I believe this does demonstrate the issue is closed and I can proceed with my testing.

I can close this issue now.
